//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehaviorHidraulic
    {
        public int id { get; set; }
        public string siteIDDatagate { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<double> ch1Value { get; set; }
        public Nullable<double> ch2Value { get; set; }
        public Nullable<double> ch3Value { get; set; }
    }
}
