//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hwmdbEntities : DbContext
    {
        public hwmdbEntities()
            : base("name=hwmdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationLog> C__MigrationLog { get; set; }
        public virtual DbSet<AbortCodeLookup> AbortCodeLookup { get; set; }
        public virtual DbSet<AccessTechnologyTypes> AccessTechnologyTypes { get; set; }
        public virtual DbSet<AccountLeakOptions> AccountLeakOptions { get; set; }
        public virtual DbSet<accounts> accounts { get; set; }
        public virtual DbSet<AccountTypeLookup> AccountTypeLookup { get; set; }
        public virtual DbSet<ActuationsPegasus> ActuationsPegasus { get; set; }
        public virtual DbSet<alarmconditions> alarmconditions { get; set; }
        public virtual DbSet<alarmforwarding> alarmforwarding { get; set; }
        public virtual DbSet<alarms> alarms { get; set; }
        public virtual DbSet<alarmTypes> alarmTypes { get; set; }
        public virtual DbSet<APIQuotas> APIQuotas { get; set; }
        public virtual DbSet<ApplicationConfigLog> ApplicationConfigLog { get; set; }
        public virtual DbSet<ApplicationSettings> ApplicationSettings { get; set; }
        public virtual DbSet<associations> associations { get; set; }
        public virtual DbSet<ATSInfoTable> ATSInfoTable { get; set; }
        public virtual DbSet<audit> audit { get; set; }
        public virtual DbSet<BandPassFilter> BandPassFilter { get; set; }
        public virtual DbSet<CategoryofPermitCodeLookup> CategoryofPermitCodeLookup { get; set; }
        public virtual DbSet<celltable> celltable { get; set; }
        public virtual DbSet<ChamberTypes> ChamberTypes { get; set; }
        public virtual DbSet<channels> channels { get; set; }
        public virtual DbSet<ChannelTypeChartOptions> ChannelTypeChartOptions { get; set; }
        public virtual DbSet<ChannelTypes> ChannelTypes { get; set; }
        public virtual DbSet<correlationAccountMeta> correlationAccountMeta { get; set; }
        public virtual DbSet<correlationPath> correlationPath { get; set; }
        public virtual DbSet<CorrelationResults> CorrelationResults { get; set; }
        public virtual DbSet<correlationTestPaths> correlationTestPaths { get; set; }
        public virtual DbSet<CountyCodes> CountyCodes { get; set; }
        public virtual DbSet<dataexport> dataexport { get; set; }
        public virtual DbSet<datapoints> datapoints { get; set; }
        public virtual DbSet<DatFileLocations> DatFileLocations { get; set; }
        public virtual DbSet<DatFiles> DatFiles { get; set; }
        public virtual DbSet<DeviceSummary> DeviceSummary { get; set; }
        public virtual DbSet<exportindex> exportindex { get; set; }
        public virtual DbSet<FavouriteSignalList> FavouriteSignalList { get; set; }
        public virtual DbSet<FavouriteSignalListData> FavouriteSignalListData { get; set; }
        public virtual DbSet<firmwareupdates> firmwareupdates { get; set; }
        public virtual DbSet<fleetreportoptions> fleetreportoptions { get; set; }
        public virtual DbSet<flowpegasus> flowpegasus { get; set; }
        public virtual DbSet<gascalorificvalues> gascalorificvalues { get; set; }
        public virtual DbSet<gaszone> gaszone { get; set; }
        public virtual DbSet<GDImportDataFileLog> GDImportDataFileLog { get; set; }
        public virtual DbSet<GDImportDataFiles> GDImportDataFiles { get; set; }
        public virtual DbSet<GNetalerts> GNetalerts { get; set; }
        public virtual DbSet<GNetalertTypes> GNetalertTypes { get; set; }
        public virtual DbSet<GNetaudit> GNetaudit { get; set; }
        public virtual DbSet<GNetchannelTypes> GNetchannelTypes { get; set; }
        public virtual DbSet<GNetcustomers> GNetcustomers { get; set; }
        public virtual DbSet<GNethubs> GNethubs { get; set; }
        public virtual DbSet<GNetlocations> GNetlocations { get; set; }
        public virtual DbSet<GNetmessages> GNetmessages { get; set; }
        public virtual DbSet<GNetmonthlyReport> GNetmonthlyReport { get; set; }
        public virtual DbSet<GNetsites> GNetsites { get; set; }
        public virtual DbSet<GNettransmitterChannels> GNettransmitterChannels { get; set; }
        public virtual DbSet<GNettransmitterData> GNettransmitterData { get; set; }
        public virtual DbSet<GNettransmitterFlushEvents> GNettransmitterFlushEvents { get; set; }
        public virtual DbSet<GNettransmitterFlushSettings> GNettransmitterFlushSettings { get; set; }
        public virtual DbSet<GNettransmitterLocations> GNettransmitterLocations { get; set; }
        public virtual DbSet<GNettransmitters> GNettransmitters { get; set; }
        public virtual DbSet<GNettransmitterTemperatureSettings> GNettransmitterTemperatureSettings { get; set; }
        public virtual DbSet<GNettransmitterTypes> GNettransmitterTypes { get; set; }
        public virtual DbSet<GNetuserRoles> GNetuserRoles { get; set; }
        public virtual DbSet<GNetusers> GNetusers { get; set; }
        public virtual DbSet<GNetuserSites> GNetuserSites { get; set; }
        public virtual DbSet<histograms> histograms { get; set; }
        public virtual DbSet<hubs> hubs { get; set; }
        public virtual DbSet<InstallationReport> InstallationReport { get; set; }
        public virtual DbSet<installsite> installsite { get; set; }
        public virtual DbSet<InvestigationAuth> InvestigationAuth { get; set; }
        public virtual DbSet<leakconfirmation> leakconfirmation { get; set; }
        public virtual DbSet<leakconfirmationassociation> leakconfirmationassociation { get; set; }
        public virtual DbSet<LeakDetectionOptions> LeakDetectionOptions { get; set; }
        public virtual DbSet<leakstatuslookup> leakstatuslookup { get; set; }
        public virtual DbSet<lnstable> lnstable { get; set; }
        public virtual DbSet<LoggerAccessTechnology> LoggerAccessTechnology { get; set; }
        public virtual DbSet<LoggerCommandHistory> LoggerCommandHistory { get; set; }
        public virtual DbSet<loggerconfigurationdata> loggerconfigurationdata { get; set; }
        public virtual DbSet<LoggerFilterConfiguration> LoggerFilterConfiguration { get; set; }
        public virtual DbSet<LoggerLevelAndSpread> LoggerLevelAndSpread { get; set; }
        public virtual DbSet<loggermeterreadings> loggermeterreadings { get; set; }
        public virtual DbSet<loggerRecordingAudit> loggerRecordingAudit { get; set; }
        public virtual DbSet<loggerrecordings> loggerrecordings { get; set; }
        public virtual DbSet<loggers> loggers { get; set; }
        public virtual DbSet<loggersecuretypes> loggersecuretypes { get; set; }
        public virtual DbSet<LoggerTypeIdentification> LoggerTypeIdentification { get; set; }
        public virtual DbSet<lookuptables> lookuptables { get; set; }
        public virtual DbSet<Maintenance> Maintenance { get; set; }
        public virtual DbSet<MaintenanceInstallation> MaintenanceInstallation { get; set; }
        public virtual DbSet<MaintenanceJob> MaintenanceJob { get; set; }
        public virtual DbSet<MaintenanceJobSitePhoto> MaintenanceJobSitePhoto { get; set; }
        public virtual DbSet<MaintenanceJobStatus> MaintenanceJobStatus { get; set; }
        public virtual DbSet<MaintenanceJobType> MaintenanceJobType { get; set; }
        public virtual DbSet<MaintenanceReports> MaintenanceReports { get; set; }
        public virtual DbSet<MaintenanceReportsServerStatus> MaintenanceReportsServerStatus { get; set; }
        public virtual DbSet<messageindex> messageindex { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<networklookup> networklookup { get; set; }
        public virtual DbSet<NGFileExportLog> NGFileExportLog { get; set; }
        public virtual DbSet<NGFileExportSchedule> NGFileExportSchedule { get; set; }
        public virtual DbSet<NGFileRejectResponse> NGFileRejectResponse { get; set; }
        public virtual DbSet<NGJobOutcome> NGJobOutcome { get; set; }
        public virtual DbSet<NGJobType> NGJobType { get; set; }
        public virtual DbSet<NGOutcomeReason> NGOutcomeReason { get; set; }
        public virtual DbSet<NGRequest> NGRequest { get; set; }
        public virtual DbSet<NGSitePhoto> NGSitePhoto { get; set; }
        public virtual DbSet<NGSiteVisit> NGSiteVisit { get; set; }
        public virtual DbSet<NGSiteVisitComment> NGSiteVisitComment { get; set; }
        public virtual DbSet<NGSiteVisitStockItems> NGSiteVisitStockItems { get; set; }
        public virtual DbSet<NGStatus> NGStatus { get; set; }
        public virtual DbSet<NGStockItems> NGStockItems { get; set; }
        public virtual DbSet<NGTransactionStatus> NGTransactionStatus { get; set; }
        public virtual DbSet<openchannelconversion> openchannelconversion { get; set; }
        public virtual DbSet<openchannelheader> openchannelheader { get; set; }
        public virtual DbSet<PipeDiameterRanges> PipeDiameterRanges { get; set; }
        public virtual DbSet<PipeMappingFromGIS> PipeMappingFromGIS { get; set; }
        public virtual DbSet<PipeMaterialTypes> PipeMaterialTypes { get; set; }
        public virtual DbSet<PipeNetwork> PipeNetwork { get; set; }
        public virtual DbSet<PipeSize> PipeSize { get; set; }
        public virtual DbSet<pmzbigtimedata> pmzbigtimedata { get; set; }
        public virtual DbSet<pmzmessagelog> pmzmessagelog { get; set; }
        public virtual DbSet<pmzoffstimedata> pmzoffstimedata { get; set; }
        public virtual DbSet<pmzpressflowdata> pmzpressflowdata { get; set; }
        public virtual DbSet<pmzpresstimedata> pmzpresstimedata { get; set; }
        public virtual DbSet<pmzsettings> pmzsettings { get; set; }
        public virtual DbSet<RaisedAsLookup> RaisedAsLookup { get; set; }
        public virtual DbSet<recentsites> recentsites { get; set; }
        public virtual DbSet<recordingspoints> recordingspoints { get; set; }
        public virtual DbSet<RepairedAsLookup> RepairedAsLookup { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<RTLTransmitters> RTLTransmitters { get; set; }
        public virtual DbSet<ScheduledReportLookup> ScheduledReportLookup { get; set; }
        public virtual DbSet<ShapeFileIconConfiguration> ShapeFileIconConfiguration { get; set; }
        public virtual DbSet<ShapeFiles> ShapeFiles { get; set; }
        public virtual DbSet<SiteCoordinates> SiteCoordinates { get; set; }
        public virtual DbSet<SiteLeakStatusHistory> SiteLeakStatusHistory { get; set; }
        public virtual DbSet<SiteLeakThresholdHistory> SiteLeakThresholdHistory { get; set; }
        public virtual DbSet<SiteLoggerUserActions> SiteLoggerUserActions { get; set; }
        public virtual DbSet<sitephotos> sitephotos { get; set; }
        public virtual DbSet<sites> sites { get; set; }
        public virtual DbSet<SMSFailures> SMSFailures { get; set; }
        public virtual DbSet<smsjobtable> smsjobtable { get; set; }
        public virtual DbSet<smsrequesttable> smsrequesttable { get; set; }
        public virtual DbSet<softwarelookup> softwarelookup { get; set; }
        public virtual DbSet<SoundVelocityLookup> SoundVelocityLookup { get; set; }
        public virtual DbSet<statuspegasus> statuspegasus { get; set; }
        public virtual DbSet<steptestcredits> steptestcredits { get; set; }
        public virtual DbSet<steptesthistory> steptesthistory { get; set; }
        public virtual DbSet<SystemNotification> SystemNotification { get; set; }
        public virtual DbSet<timepegasus> timepegasus { get; set; }
        public virtual DbSet<TMAOptions> TMAOptions { get; set; }
        public virtual DbSet<torancounts> torancounts { get; set; }
        public virtual DbSet<unitslookup> unitslookup { get; set; }
        public virtual DbSet<user_device> user_device { get; set; }
        public virtual DbSet<UserChannelChartTypes> UserChannelChartTypes { get; set; }
        public virtual DbSet<UserNotificationAcknowledgement> UserNotificationAcknowledgement { get; set; }
        public virtual DbSet<userpasswords> userpasswords { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<UserUnitLookup> UserUnitLookup { get; set; }
        public virtual DbSet<witsendpoints> witsendpoints { get; set; }
        public virtual DbSet<witssitedetails> witssitedetails { get; set; }
        public virtual DbSet<WorkOrderLeakConfAssociation> WorkOrderLeakConfAssociation { get; set; }
        public virtual DbSet<WWAlarmSettingsTable> WWAlarmSettingsTable { get; set; }
        public virtual DbSet<Measurements> Measurements { get; set; }
        public virtual DbSet<Survey> Survey { get; set; }
        public virtual DbSet<ApplicationLookup> ApplicationLookup { get; set; }
        public virtual DbSet<MaintenanceInstallationReportStatus> MaintenanceInstallationReportStatus { get; set; }
        public virtual DbSet<MaintenanceInstallationType> MaintenanceInstallationType { get; set; }
        public virtual DbSet<MaintenanceJobStatusComment> MaintenanceJobStatusComment { get; set; }
        public virtual DbSet<NGFileSequence> NGFileSequence { get; set; }
        public virtual DbSet<Predictive> Predictive { get; set; }
        public virtual DbSet<Predictive_AlarmCount> Predictive_AlarmCount { get; set; }
        public virtual DbSet<Predictive_Audit> Predictive_Audit { get; set; }
        public virtual DbSet<PredictiveAlarmSetting> PredictiveAlarmSetting { get; set; }
        public virtual DbSet<tempchannels> tempchannels { get; set; }
        public virtual DbSet<tempsiteList> tempsiteList { get; set; }
    }
}
