//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContratoMantenimientoEntities1 : DbContext
    {
        public ContratoMantenimientoEntities1()
            : base("name=ContratoMantenimientoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BehaviorHidraulic> BehaviorHidraulic { get; set; }
        public virtual DbSet<BehaviorInstrumentation> BehaviorInstrumentation { get; set; }
        public virtual DbSet<SitesMtto> SitesMtto { get; set; }
        public virtual DbSet<TaskSuppliesUsed> TaskSuppliesUsed { get; set; }
        public virtual DbSet<TechnicalServices> TechnicalServices { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<TareasPreventivas> TareasPreventivas { get; set; }
    }
}
