//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitesMtto
    {
        public int id { get; set; }
        public string siteIDDatagate { get; set; }
        public string idFieldBeat { get; set; }
        public string addressDatagate { get; set; }
        public Nullable<System.DateTime> createDateDatagate { get; set; }
        public string typeDevice { get; set; }
        public Nullable<double> latitudeSite { get; set; }
        public Nullable<double> longitudeSite { get; set; }
        public string MeasuresDevice { get; set; }
    }
}
